apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pvc
  namespace: narasimha
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
