apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claims
  namespace: narasimha
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
