apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: Loadbalancer
  selector:
    role: frontend
